# Generated by Django 2.1.7 on 2019-02-22 23:56

from django.db import migrations, models
import django.db.models.deletion
import djgeojson.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.FloatField(blank=True, null=True)),
                ('geom', djgeojson.fields.MultiPolygonField(blank=True, null=True)),
                ('epsa', models.ForeignKey(help_text='Epsa que presta los servicios en esta área.', on_delete=django.db.models.deletion.CASCADE, to='performance.EPSA')),
            ],
            options={
                'verbose_name': 'Área de Prestación de Servicio',
                'verbose_name_plural': 'Áreas de Prestación de Servicio',
                'ordering': ['epsa__category', 'epsa__code'],
            },
        ),
    ]
